# Generated by Django 5.2.2 on 2025-07-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riasec_type', models.CharField(max_length=3)),
                ('program_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skills', models.TextField(help_text='Перечислите навыки через запятую')),
                ('ege_subjects', models.TextField(help_text='Необходимые ЕГЭ (через запятую): Математика, Русский язык, Физика и т.д.')),
                ('entrance_tests', models.TextField(blank=True, default='', help_text='Необходимые ВИ (через запятую)...')),
                ('professions', models.TextField(help_text='Перечислите профессии через запятую')),
                ('program_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RIASECResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('realistic', models.PositiveIntegerField(default=0)),
                ('investigative', models.PositiveIntegerField(default=0)),
                ('artistic', models.PositiveIntegerField(default=0)),
                ('social', models.PositiveIntegerField(default=0)),
                ('enterprising', models.PositiveIntegerField(default=0)),
                ('conventional', models.PositiveIntegerField(default=0)),
                ('primary_type', models.CharField(choices=[('R', 'Реалистичный'), ('I', 'Интеллектуальный'), ('A', 'Артистичный'), ('S', 'Социальный'), ('E', 'Предприимчивый'), ('C', 'Конвенциональный')], max_length=1)),
                ('secondary_type', models.CharField(choices=[('R', 'Реалистичный'), ('I', 'Интеллектуальный'), ('A', 'Артистичный'), ('S', 'Социальный'), ('E', 'Предприимчивый'), ('C', 'Конвенциональный')], max_length=1)),
                ('tertiary_type', models.CharField(choices=[('R', 'Реалистичный'), ('I', 'Интеллектуальный'), ('A', 'Артистичный'), ('S', 'Социальный'), ('E', 'Предприимчивый'), ('C', 'Конвенциональный')], max_length=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат теста RIASEC',
                'verbose_name_plural': 'Результаты тестов RIASEC',
                'ordering': ['-date_taken'],
            },
        ),
    ]
