# Generated by Django 5.2.2 on 2025-07-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrecommendation',
            name='entrance_tests',
            field=models.TextField(blank=True, default='', help_text='Необходимые ВИ (через запятую): Информационные технологии, Техническая физика и т. д.'),
        ),
    ]
